name: Pull Request

on: [pull_request]

jobs:
  pull_request:
    runs-on: ubuntu-latest
    
    steps:
      - run: echo "${{ toJson(github.event.action) }}"
      
      - run: echo "${{ toJson(github.event) }}"
