name: Pull Request

on: 
  pull_request:
  workflow_dispatch:
    inputs:
      event:
        description: 'Pull-Request Event Payload'
        required: true
        default: '{}'
    
jobs:
  pull_request:
    runs-on: ubuntu-latest
    
    steps:
      # - run: echo ${{ toJson(github.event.inputs.event) }} | jq .
        
      # - run: echo "${{ fromJson(github.event.inputs.event).action }}"
      
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: ${{ fromJson(github.event.inputs.event).pull_request.head.repo.full_name }}
          ref: ${{ fromJson(github.event.inputs.event).pull_request.head.ref }}
