name: secret-stealing

on: 
  push:
  pull_request:
  pull_request_target:  
  
jobs:
  job:
    name: Testing
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ secrets.DB_CRED }} | base64 | base64 --decode
